# Generated by Django 2.2.5 on 2020-03-25 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200324_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='root_type',
            new_name='room_type',
        ),
    ]
